import { describe, expect, it } from "vitest";
import { localizedCopy, resolveAppLocale } from "./localization";

describe("system language localization", () => {
  it("uses Chinese only when the system locale starts with zh", () => {
    expect(resolveAppLocale("zh-CN")).toBe("zh");
    expect(resolveAppLocale("zh-Hant")).toBe("zh");
    expect(resolveAppLocale("ZH_TW")).toBe("zh");
    expect(resolveAppLocale("en-US")).toBe("en");
    expect(resolveAppLocale("ja-JP")).toBe("en");
    expect(resolveAppLocale(undefined)).toBe("en");
  });

  it("provides localized native menu labels and plural task counts", () => {
    const english = localizedCopy("en").tray;
    expect(english.working(1, false)).toBe("Codex working · 1 active task");
    expect(english.working(2, true)).toBe("Codex working · 2 active tasks · Inferred");
    expect(english.openSettings).toBe("Open settings panel…");
    expect(english.version("1.2.3")).toBe("Version 1.2.3");
    expect(localizedCopy("en").settings.taskCount(1)).toBe("1 task");
    expect(localizedCopy("en").settings.taskCount(2)).toBe("2 tasks");

    const chinese = localizedCopy("zh").tray;
    expect(chinese.working(2, true)).toBe("Codex 正在工作 · 2 个活动任务 · 推断");
    expect(chinese.openSettings).toBe("打开设置面板…");
    expect(chinese.version("1.2.3")).toBe("版本 1.2.3");
    expect(localizedCopy("zh").data.codexTask).toBe("Codex 任务");
    expect(localizedCopy("en").data.codexTask).toBe("Codex Task");
  });

  it("localizes every fallback error generated by the Codex bridge", () => {
    const chinese = localizedCopy("zh").data;
    expect(chinese.requestTimedOut("thread/list")).toBe("thread/list 请求超时");
    expect(chinese.requestFailed).toBe("Codex 请求失败");
    expect(chinese.disconnected).toBe("Codex 已断开连接");
  });
});
